[package]
name = "distribuito"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.208", features = ["derive"] }
tokio = { version = "1", features = ["full"] }
serde_json = "1.0.125"
axum = "0.7.5"
home = "0.5.9"
log = "0.4"
std-logger = "0.5.3"